version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/packages/web'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/packages/vue'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/packages/native'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/packages/reactivecore'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
